PREFIX dct: <http://purl.org/dc/terms>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
SELECT *
WHERE {
?s dct:modified ?date .
?b dc:title ?title .
FILTER ( ?date < "2014-01-01"^^xsd:date && REGEX(str(?title) , "%water%"))
}
