PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/geosparql/function/>
SELECT *	
WHERE {
?s geo:hasGeometry ?fWKT .
FILTER (geof:sfContains(?fWKT, "BOX2D(-5.01 50.23, 1.69 56.12)"^^geo:wktLiteral))	
}
